### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by weilinzung** [netcore/frontend-base#2] opened 2017-12-02 20:32 UTC
follow everything like the docs, but I get `Cannot GET /`.

on the terminal has `jekyll 3.6.2 | Error:  The minima theme could not be found.` message~

**Comment by vladislavsz** [comment] 2017-12-02 20:42
Hi @weilinzung.
On some systems the error is caused by [these 2 lines](https://github.com/netcore/frontend-base/blob/master/_config.yml#L20-L21) inside of **_config.yml** file.
You can remove them and the error will be gone.

This will get fixed in the next version 1.0.1.

Thanks.

**Comment by weilinzung** [comment] 2017-12-02 21:05
ok, thanks~

hopefully, these functions would also added to the new one:

- combined all JS into one JS on production or dev

- add version number to all assets which could fixed cache issue

- minify html & remove comment lines

- remove `Jekyll new minima` required setup (make it clean as possible as a starter)

- Bootstrap Assets seems all on wrong path now _(no need to import each single one, just need to import the `boostrap.js` & `boostrap.css` from dist folder would enough)_

- if possible, please see if anyways to make an automation to inject plugin's CSS and JS after run `yarn add xxx`, example: run `yarn add plugin1.0`, after that run `gulp watch` which will automatic add this plugin's CSS & Js files as IMPORTs~

- update the docs to have more details (steps by steps setup, install git plugins...)

Anyway a very nice & detail project.

**Comment by vladislavsz** [comment] 2017-12-02 21:45
Hi again.

> combined all JS into one JS on production or dev

It does indeed seem like combining everything into just 1 file would be better.

>add version number to all assets which could fixed cache issue

Currently caching is denied with a help of Jekyll by a timestamp query which is added to the assets. Asset file name hashing might come in the future updates.

> minify html & remove comment lines

Not too sure about this one yet. _Might_ get added in one of the next versions but don't take my word on it.

>remove `Jekyll new minima` required setup (make it clean as possible as a starter)

Yes. As I stated in the first reply, this will get fixed in the next version.

>Bootstrap Assets seems all on wrong path now _(no need to import each single one, just need to import the `boostrap.js` & `boostrap.css` from dist folder would enough)_

I don't really get what you mean by them being "on wrong path". It seems to be working just fine for me and my colleagues.

As for including all of the CSS and JS - no. We import them separately for a good reason - to try and keep only components that are actually in use, thus minimizing the output file size.

>if possible, please see if anyways to make an automation to inject plugin's CSS and JS after run `yarn add xxx`, example: run `yarn add plugin1.0`, after that run `gulp watch` which will automatic add this plugin's CSS & Js files as IMPORTs~

You see, custom packages often have very different file structure compared to one another and it would be quite hard to automatically **and correctly** gather all the necessary CSS and output it inside the vendor folder. It is easier for JS as you should be good to go by just adding a `import Variable from 'plugin'` line.

You can download a package in a separate command prompt window, import everything that is needed and it should "pick up" the new files.

So I guess the answer for this request would be a "no".

>update the docs to have more details (steps by steps setup, install git plugins...)

Could you clarify which steps you were confused by / stuck on exactly?

>Anyway a very nice & detail project.

Thanks, that's great to hear!

**Comment by vladislavsz** [comment] 2017-12-02 21:49
For a further discussion please create a separate issue.

**Closed as completed** 2017-12-02 21:50 UTC
Labels: bug
